### Create instance
POST http://localhost:8080/AssureIDService/Document/Instance
Content-Type: application/json

{
}

> {%
  client.global.set("instance_id", response.body.trim().replace(/"/g, ""));
  client.log(client.global.get("instance_id"))
%}


### Post front
POST http://localhost:8080/AssureIDService/Document/{{instance_id}}/Image?side=front&light=0

{
  "front": {},
  "back": {},
  "result": {
    "ognlExpression": "#this.alerts.{? #this.key==\"2D Barcode Content\"}[0].result=-10"
  }
}

### Post back
POST http://localhost:8080/AssureIDService/Document/{{instance_id}}/Image?side=back&light=0

{
  "front": {},
  "back": {},
  "result": {
    "ognlExpression": "#this.alerts.{? #this.key==\"2D Barcode Content\"}[0].result=-10"
  }
}

### Get Result
GET http://localhost:8080/AssureIDService/Document/{{instance_id}}
Content-Type: application/json

> {%

  client.log(response.body)
%}
